Alex testbranch
WeFridge/WeFridge pull request #51
Opened 2021-12-11 17:11 UTC by AlexTerhar

icon is set, background will remain transparent, not changable, icon is green, Chanel is set 
If its possible, someone else can finish the pull

2021-12-11 18:42 UTC, frcroth commented
So this is not yet complete?

2021-12-12 13:56 UTC, AlexTerhar commented
it is complete. but some desired changes are not possible due to the android oreo version

2021-12-13 15:39 UTC, frcroth requested changes

2021-12-13 15:39 UTC, frcroth commented on app/src/main/java/app/wefridge/wefridge/MainActivity.kt
> +    @SuppressLint("StringFormatInvalid")
why this?

2021-12-13 15:39 UTC, frcroth commented on app/src/main/java/app/wefridge/wefridge/MainActivity.kt
> +                Log.d(R.string.TAG_Main.toString(), msg)
```suggestion
                Log.d(R.string.TAB_Main.toString(), if (task.isSuccessful) "Subscribed to ${user.uid}" else "Failed to subscribe")
```

2021-12-13 15:39 UTC, frcroth commented on app/src/main/java/app/wefridge/wefridge/MainActivity.kt
> +        Log.d("FCM", "This is the user id: ${user.uid} ")
```suggestion
        Log.d("FCM", "User ${user.uid} successfully signed in")
```

2021-12-13 15:39 UTC, frcroth commented on app/src/main/java/app/wefridge/wefridge/MyFirebaseMessagingService.kt
> +class MyFirebaseMessagingService : FirebaseMessagingService() {
Change name. Something like WeFridgeMessagingService would be better.

2021-12-13 15:39 UTC, frcroth commented on app/src/main/java/app/wefridge/wefridge/MyFirebaseMessagingService.kt
> +    // [START receive_message]
What do these comments mean?

2021-12-13 15:39 UTC, frcroth commented on app/src/main/java/app/wefridge/wefridge/MyFirebaseMessagingService.kt
> +    @SuppressLint("RemoteViewLayout")
Why this?

2021-12-13 15:39 UTC, frcroth commented on app/src/main/java/app/wefridge/wefridge/MyFirebaseMessagingService.kt
> +    @SuppressLint("UnspecifiedImmutableFlag")
Why this?

2021-12-13 15:39 UTC, frcroth commented on app/src/main/java/app/wefridge/wefridge/MyFirebaseMessagingService.kt
> +    // [START receive_message]
What do these comments mean?

2021-12-13 15:39 UTC, frcroth commented on app/src/main/java/app/wefridge/wefridge/MyFirebaseMessagingService.kt
> +        val intent = Intent(this, MainActivity::class.java)
Is the code of this method original or is there some source?

2021-12-13 15:39 UTC, frcroth commented on app/src/main/res/values/strings.xml
> +    <string name="fcm_message">Hier könnte deine Werbung stehen</string>
Unused I think

2021-12-13 15:39 UTC, frcroth commented on app/src/main/res/values/strings.xml
> +    <string name="TAG_Main">Main_Activity:</string>
I don't think the TAGs need to be here

2021-12-13 15:39 UTC, frcroth commented on app/src/main/res/values/strings.xml
> +    <string name="default_notification_channel_id">app.wefridge.wefridge</string>
Also may not be the right place, just define this in the class I would say.

2021-12-13 17:25 UTC, closed without merging

2021-12-13 17:25 UTC, AlexTerhar commented
i made a new one with changes